CREATE TABLE utility_bills (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    deleted_at DATETIME(6) NULL,
    bill_no VARCHAR(50) NOT NULL,
    org_unit_id BIGINT NOT NULL,
    billing_zone_id BIGINT NOT NULL,
    connection_id BIGINT NOT NULL,
    account_number VARCHAR(50) NOT NULL,
    customer_name VARCHAR(255) NULL,
    tariff_id BIGINT NULL,
    tariff_name VARCHAR(255) NULL,
    billing_month VARCHAR(7) NOT NULL,
    billing_date DATE NOT NULL,
    previous_reading INT NULL,
    current_reading INT NULL,
    units_consumed INT NULL,
    usage_charge DECIMAL(14,2) NOT NULL DEFAULT 0,
    fixed_charge DECIMAL(14,2) NOT NULL DEFAULT 0,
    late_fee_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    red_bill_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    total_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    late_fee_method VARCHAR(255) NULL,
    red_bill_method VARCHAR(255) NULL,
    custom_note VARCHAR(1000) NULL,
    status ENUM('OPEN','CLOSED','REVERSED') NOT NULL DEFAULT 'OPEN',
    meter_read_date DATE NULL,
    closed_date DATE NULL,
    CONSTRAINT uq_utility_bills_org_zone_account_month UNIQUE (org_unit_id, billing_zone_id, account_number, billing_month)
);