package me.nimnakse.water_management.utility_bills.service.impl;
import java.math.BigDecimal; import java.math.RoundingMode; import java.time.*; import java.time.temporal.ChronoUnit; import java.util.*; import java.util.stream.Collectors;
import me.nimnakse.water_management.billing_zones.entity.BillingZone; import me.nimnakse.water_management.billing_zones.repository.BillingZoneRepository; import me.nimnakse.water_management.common.exception.*; import me.nimnakse.water_management.connections.entity.*; import me.nimnakse.water_management.connections.repository.ConnectionRepository; import me.nimnakse.water_management.security.*; import me.nimnakse.water_management.sales.invoices.dto.request.RecurringInvoiceToggleReq; import me.nimnakse.water_management.sales.invoices.entity.*; import me.nimnakse.water_management.sales.invoices.service.SalesInvoiceService; import me.nimnakse.water_management.tariffs.entity.*; import me.nimnakse.water_management.tariffs.repository.TariffRepository; import me.nimnakse.water_management.utility_bills.dto.request.*; import me.nimnakse.water_management.utility_bills.dto.response.*; import me.nimnakse.water_management.utility_bills.entity.*; import me.nimnakse.water_management.utility_bills.repository.*; import me.nimnakse.water_management.utility_bills.service.UtilityBillService; import me.nimnakse.water_management.users.entity.User; import me.nimnakse.water_management.users.repository.UserRepository; import org.springframework.security.core.Authentication; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class UtilityBillServiceImpl implements UtilityBillService {
  private final UtilityBillRepository billRepository; private final ConnectionRepository connectionRepository; private final BillingZoneRepository billingZoneRepository; private final TariffRepository tariffRepository; private final OrganizationAccessService accessService; private final SalesInvoiceService salesInvoiceService; private final PasswordEncoder passwordEncoder; private final UserRepository userRepository;
  public UtilityBillServiceImpl(UtilityBillRepository billRepository, ConnectionRepository connectionRepository, BillingZoneRepository billingZoneRepository, TariffRepository tariffRepository, OrganizationAccessService accessService, SalesInvoiceService salesInvoiceService, PasswordEncoder passwordEncoder, UserRepository userRepository){this.billRepository=billRepository;this.connectionRepository=connectionRepository;this.billingZoneRepository=billingZoneRepository;this.tariffRepository=tariffRepository;this.accessService=accessService;this.salesInvoiceService=salesInvoiceService;this.passwordEncoder=passwordEncoder;this.userRepository=userRepository;}
  @Override @Transactional(readOnly=true) public List<UtilityBillZoneSummaryRes> listZoneSummaries(Long orgUnitId, List<Long> billingZoneIds){ Long resolved=resolveOrgUnitId(orgUnitId); Set<Long> filter=billingZoneIds==null?Set.of():billingZoneIds.stream().filter(Objects::nonNull).collect(Collectors.toSet()); List<Connection> connections=connectionRepository.findByOrgUnitId(resolved).stream().filter(c->c.getDeletedAt()==null).filter(c->filter.isEmpty()||filter.contains(c.getBillingZoneId())).toList(); return connections.stream().collect(Collectors.groupingBy(Connection::getBillingZoneId)).entrySet().stream().map(e->{ Long zoneId=e.getKey(); BillingZone zone=billingZoneRepository.findById(zoneId).orElse(null); UtilityBill latest=billRepository.findTopByOrgUnitIdAndBillingZoneIdAndDeletedAtIsNullOrderByCreatedAtDesc(resolved,zoneId).orElse(null); LocalDate last=latest==null||latest.getCreatedAt()==null?null:latest.getCreatedAt().atZone(ZoneOffset.systemDefault()).toLocalDate(); Long elapsed=last==null?null:ChronoUnit.DAYS.between(last, LocalDate.now()); long pending=e.getValue().stream().filter(c->c.getStatus()==ConnectionStatus.PENDING).count(); long active=e.getValue().stream().filter(c->c.getStatus()==ConnectionStatus.CONNECTED).count(); long disconnected=e.getValue().stream().filter(c->c.getStatus()==ConnectionStatus.DISCONNECTED).count(); return new UtilityBillZoneSummaryRes(zoneId, zone!=null?zone.getZoneName():"Unknown", last, elapsed, pending, active, disconnected, resolveLateFeeMethod(latest==null?null:latest.getTariffId()), resolveRedBillMethod(latest==null?null:latest.getTariffId())); }).sorted(Comparator.comparing(UtilityBillZoneSummaryRes::billingZoneName)).toList(); }
  @Override @Transactional public List<UtilityBillRes> generate(UtilityBillGenerateReq request){ Long resolved=resolveOrgUnitId(request.orgUnitId()); verifyPassword(request.password()); YearMonth month=parseMonth(request.operationMonth()); LocalDate billingDate=request.billingDate()==null?LocalDate.now():request.billingDate(); Set<Long> zones=request.billingZoneIds()==null||request.billingZoneIds().isEmpty()?connectionRepository.findByOrgUnitId(resolved).stream().map(Connection::getBillingZoneId).collect(Collectors.toSet()):request.billingZoneIds().stream().filter(Objects::nonNull).collect(Collectors.toSet()); if(request.stopRecurringInvoiceIds()!=null){ request.stopRecurringInvoiceIds().stream().filter(Objects::nonNull).forEach(id->salesInvoiceService.toggleRecurring(id,new RecurringInvoiceToggleReq(false))); } List<UtilityBillRes> out=new ArrayList<>(); for(Connection c: connectionRepository.findByOrgUnitId(resolved).stream().filter(x->x.getDeletedAt()==null).filter(x->zones.contains(x.getBillingZoneId())).toList()){ String monthKey=month.toString(); if(billRepository.findTopByOrgUnitIdAndBillingZoneIdAndAccountNumberAndBillingMonthAndDeletedAtIsNullOrderByCreatedAtDesc(resolved,c.getBillingZoneId(),c.getAccountNumber(),monthKey).isPresent()) continue; Tariff tariff=tariffRepository.findById(c.getTariffId()).orElseThrow(()->new NotFoundException("Tariff not found","Tariff not found",ErrorCode.NOT_FOUND)); UtilityBill bill=new UtilityBill(); bill.setBillNo(nextBillNo(resolved)); bill.setOrgUnitId(resolved); bill.setBillingZoneId(c.getBillingZoneId()); bill.setConnectionId(c.getId()); bill.setAccountNumber(c.getAccountNumber()); bill.setCustomerName(c.getHouseName()!=null?c.getHouseName():c.getAccountNumber()); bill.setTariffId(tariff.getId()); bill.setTariffName(tariff.getName()); bill.setBillingMonth(monthKey); bill.setBillingDate(billingDate); bill.setPreviousReading(latestClosedReading(resolved,c.getId())); bill.setCurrentReading(null); bill.setUnitsConsumed(null); bill.setUsageCharge(zero()); bill.setFixedCharge(zero()); bill.setLateFeeAmount(zero()); bill.setRedBillAmount(zero()); bill.setTotalAmount(zero()); bill.setLateFeeMethod(resolveLateFeeMethod(tariff.getId())); bill.setRedBillMethod(resolveRedBillMethod(tariff.getId())); bill.setCustomNote(trim(request.customNote())); bill.setStatus(UtilityBillStatus.OPEN); bill.setCreatedBy(currentUserId()); out.add(toRes(billRepository.save(bill))); } return out; }
  @Override @Transactional(readOnly=true) public List<UtilityBillRes> listOpen(Long orgUnitId, Long billingZoneId){ return listByStatus(orgUnitId,billingZoneId,UtilityBillStatus.OPEN); }
  @Override @Transactional(readOnly=true) public List<UtilityBillRes> listClosed(Long orgUnitId, Long billingZoneId){ return listByStatus(orgUnitId,billingZoneId,UtilityBillStatus.CLOSED); }
  @Override @Transactional public UtilityBillRes meterRead(Long billId, UtilityBillMeterReadReq request){ UtilityBill bill=getBill(billId); if(bill.getStatus()!=UtilityBillStatus.OPEN) throw new BadRequestException("Only open bills can be read","Only open bills can be read"); if(request.currentReading()==null) throw new BadRequestException("Current reading is required","Current reading is required"); Tariff tariff=tariffRepository.findById(bill.getTariffId()).orElseThrow(()->new NotFoundException("Tariff not found","Tariff not found",ErrorCode.NOT_FOUND)); Calculation calc=calculateFromTariff(tariff,bill.getPreviousReading()==null?0:bill.getPreviousReading(),request.currentReading()); bill.setCurrentReading(request.currentReading()); bill.setUnitsConsumed(calc.units()); bill.setUsageCharge(calc.usage()); bill.setFixedCharge(calc.fixed()); bill.setLateFeeAmount(calc.lateFee()); bill.setRedBillAmount(calc.redBill()); bill.setTotalAmount(calc.total()); bill.setMeterReadDate(request.meterReadDate()==null?LocalDate.now():request.meterReadDate()); bill.setCustomNote(blankToNull(request.note())==null?bill.getCustomNote():request.note().trim()); bill.setStatus(UtilityBillStatus.CLOSED); bill.setClosedDate(LocalDate.now()); bill.setCreatedBy(currentUserId()); return toRes(billRepository.save(bill)); }
  @Override @Transactional public UtilityBillRes reopen(Long billId){ UtilityBill bill=getBill(billId); bill.setStatus(UtilityBillStatus.OPEN); bill.setCurrentReading(null); bill.setUnitsConsumed(null); bill.setUsageCharge(zero()); bill.setFixedCharge(zero()); bill.setLateFeeAmount(zero()); bill.setRedBillAmount(zero()); bill.setTotalAmount(zero()); bill.setMeterReadDate(null); bill.setClosedDate(null); return toRes(billRepository.save(bill)); }
  @Override @Transactional(readOnly=true) public UtilityBillCalculatorRes calculate(UtilityBillCalculatorReq request){ Tariff tariff=tariffRepository.findById(request.tariffId()).orElseThrow(()->new NotFoundException("Tariff not found","Tariff not found",ErrorCode.NOT_FOUND)); Calculation calc=calculateFromTariff(tariff,request.previousReading()==null?0:request.previousReading(),request.currentReading()==null?0:request.currentReading()); return new UtilityBillCalculatorRes(tariff.getId(),request.previousReading(),request.currentReading(),calc.units(),calc.usage(),calc.fixed(),calc.lateFee(),calc.redBill(),calc.total(),resolveLateFeeMethod(tariff.getId()),resolveRedBillMethod(tariff.getId()),calc.lines()); }
  private List<UtilityBillRes> listByStatus(Long orgUnitId, Long billingZoneId, UtilityBillStatus status){ Long resolved=resolveOrgUnitId(orgUnitId); return billRepository.findByOrgUnitIdAndStatusAndDeletedAtIsNullOrderByBillingZoneIdAscAccountNumberAsc(resolved,status).stream().filter(b->billingZoneId==null||Objects.equals(b.getBillingZoneId(),billingZoneId)).map(this::toRes).toList(); }
  private UtilityBill getBill(Long billId){ UtilityBill bill=billRepository.findById(billId).orElseThrow(()->new NotFoundException("Bill not found","Bill not found",ErrorCode.NOT_FOUND)); accessService.enforceOrgUnitAccess(bill.getOrgUnitId()); return bill; }
  private Long resolveOrgUnitId(Long orgUnitId){ Long resolved=orgUnitId!=null?orgUnitId:accessService.resolveOrgUnitId(); if(resolved==null) throw new BadRequestException("Organization unit is required","Organization unit is required"); accessService.enforceOrgUnitAccess(resolved); return resolved; }
  private void verifyPassword(String password){ if(password==null||password.isBlank()) throw new BadRequestException("Password is required","Password is required"); Authentication auth=SecurityContextHolder.getContext().getAuthentication(); if(auth==null||!(auth.getPrincipal() instanceof UserPrincipal p)) throw new BadRequestException("User not authenticated","User not authenticated"); if(!passwordEncoder.matches(password,p.getPassword())) throw new BadRequestException("Invalid password","Invalid password"); }
  private YearMonth parseMonth(String value){ return value==null||value.isBlank()?YearMonth.now():YearMonth.parse(value); }
  private int latestClosedReading(Long orgUnitId, Long connectionId){ return billRepository.findByOrgUnitIdAndStatusAndDeletedAtIsNullOrderByBillingZoneIdAscAccountNumberAsc(orgUnitId,UtilityBillStatus.CLOSED).stream().filter(b->Objects.equals(b.getConnectionId(),connectionId)).max(Comparator.comparing(UtilityBill::getCreatedAt)).map(UtilityBill::getCurrentReading).orElse(0); }
  private String nextBillNo(Long orgUnitId){ String prefix="UB-"; int next=billRepository.findByOrgUnitIdAndStatusAndDeletedAtIsNullOrderByBillingZoneIdAscAccountNumberAsc(orgUnitId,UtilityBillStatus.OPEN).stream().map(UtilityBill::getBillNo).filter(Objects::nonNull).filter(no->no.startsWith(prefix)).map(no->no.substring(prefix.length())).filter(this::isNumeric).mapToInt(Integer::parseInt).max().orElse(0)+1; return String.format("%s%06d",prefix,next); }
  private boolean isNumeric(String value){ try{Integer.parseInt(value); return true;}catch(Exception ex){return false;} }
  private String resolveLateFeeMethod(Long tariffId){ if(tariffId==null) return null; return tariffRepository.findById(tariffId).map(t->t.getLateFees().isEmpty()?null:Optional.ofNullable(t.getLateFees().get(0).getChargingMethod()).orElse(t.getLateFees().get(0).getName())).orElse(null); }
  private String resolveRedBillMethod(Long tariffId){ if(tariffId==null) return null; return tariffRepository.findById(tariffId).map(t->t.getLateFees().isEmpty()?null:(Boolean.TRUE.equals(t.getLateFees().get(0).isApplyRedBill())?"Red Bill":"Normal Bill")).orElse(null); }
  private Calculation calculateFromTariff(Tariff tariff, int previous, int current){ int max=(int)Math.pow(10, tariff.getMeterDigits()==null||tariff.getMeterDigits()<=0?4:tariff.getMeterDigits()); int units=current>=previous?current-previous:(current+max)-previous; if(units<0) units=0; List<TariffSlab> slabs=tariff.getSlabs()==null?List.of():tariff.getSlabs().stream().sorted(Comparator.comparing(TariffSlab::getFromUnit)).toList(); List<UtilityBillCalculatorLineRes> lines=new ArrayList<>(); BigDecimal usage=zero(), fixed=zero(), late=zero(), red=zero(); if(units==0){ usage=money(tariff.getZeroConsumptionCharge()); fixed=sumRentals(slabs); return new Calculation(units,usage,fixed,late,red,usage.add(fixed),lines); } int remaining=units; for(int i=0;i<slabs.size() && remaining>0;i++){ TariffSlab slab=slabs.get(i); int slabUnits=Math.max(0, slab.getToUnit()-slab.getFromUnit()+1); int take=Math.min(remaining, slabUnits>0?slabUnits:remaining); BigDecimal rate=money(slab.getCharge()); BigDecimal amount=rate.multiply(BigDecimal.valueOf(take)).setScale(2,RoundingMode.HALF_UP); lines.add(new UtilityBillCalculatorLineRes(slab.getFromUnit(), slab.getToUnit(), take, rate, amount)); usage=usage.add(amount); fixed=fixed.add(money(slab.getRental())); remaining-=take; } if(remaining>0 && !slabs.isEmpty()){ TariffSlab last=slabs.get(slabs.size()-1); BigDecimal rate=money(last.getCharge()); BigDecimal amount=rate.multiply(BigDecimal.valueOf(remaining)).setScale(2,RoundingMode.HALF_UP); lines.add(new UtilityBillCalculatorLineRes(last.getToUnit()+1, last.getToUnit()+remaining, remaining, rate, amount)); usage=usage.add(amount); fixed=fixed.add(money(last.getRental())); } return new Calculation(units,usage,fixed,late,red,usage.add(fixed),lines); }
  private BigDecimal sumRentals(List<TariffSlab> slabs){ return slabs.stream().map(TariffSlab::getRental).map(this::money).reduce(zero(), BigDecimal::add); }
  private BigDecimal money(Double v){ return v==null?zero():BigDecimal.valueOf(v).setScale(2,RoundingMode.HALF_UP); }
  private BigDecimal zero(){ return BigDecimal.ZERO.setScale(2,RoundingMode.HALF_UP); }
  private String trim(String value){ if(value==null) return null; String t=value.trim(); return t.isEmpty()?null:t; }
  private String blankToNull(String value){ return trim(value); }
  private UtilityBillRes toRes(UtilityBill bill){ return new UtilityBillRes(bill.getId(),bill.getBillNo(),bill.getOrgUnitId(),bill.getBillingZoneId(),billingZoneRepository.findById(bill.getBillingZoneId()).map(BillingZone::getZoneName).orElse("Unknown"),bill.getConnectionId(),bill.getAccountNumber(),bill.getCustomerName(),bill.getTariffId(),bill.getTariffName(),bill.getBillingMonth(),bill.getBillingDate(),bill.getPreviousReading(),bill.getCurrentReading(),bill.getUnitsConsumed(),money(bill.getUsageCharge()==null?0.0:bill.getUsageCharge().doubleValue()),money(bill.getFixedCharge()==null?0.0:bill.getFixedCharge().doubleValue()),money(bill.getLateFeeAmount()==null?0.0:bill.getLateFeeAmount().doubleValue()),money(bill.getRedBillAmount()==null?0.0:bill.getRedBillAmount().doubleValue()),money(bill.getTotalAmount()==null?0.0:bill.getTotalAmount().doubleValue()),bill.getLateFeeMethod(),bill.getRedBillMethod(),bill.getCustomNote(),bill.getStatus(),bill.getMeterReadDate(),bill.getClosedDate(),resolveUsername(bill.getCreatedBy()),bill.getCreatedAt(),bill.getUpdatedAt()); }
  private Map<Long, String> loadUsernames(Set<Long> userIds){ if(userIds==null||userIds.isEmpty()) return Map.of(); return userRepository.findAllById(userIds).stream().collect(Collectors.toMap(User::getId, User::getUsername)); }
  private String resolveUsername(Long userId){ if(userId==null) return null; return userRepository.findById(userId).map(User::getUsername).orElse(null); }
  private Long currentUserId(){ Authentication auth=SecurityContextHolder.getContext().getAuthentication(); if(auth==null||!(auth.getPrincipal() instanceof UserPrincipal p)) return null; return p.getUser().getId(); }
  private record Calculation(int units, BigDecimal usage, BigDecimal fixed, BigDecimal lateFee, BigDecimal redBill, BigDecimal total, List<UtilityBillCalculatorLineRes> lines){}
}
