package me.nimnakse.water_management.service_requests.entity;

public enum ServiceRequestResolutionType {
    NEW_SERVICE_CONNECTION_INSTALLED,
    SERVICE_DISCONNECTED_DUE_TO_NON_PAYMENT,
    SERVICE_DISCONNECTED_UPON_CUSTOMER_REQUEST,
    SERVICE_RECONNECTED,
    NEW_METER_REPLACED,
    METER_REPAIRED,
    METER_READING_ADJUSTED,
    SERVICE_LINE_REPAIRED,
    MAIN_LINE_REPAIRED,
    OTHER_RESOLUTION
}
