package me.nimnakse.water_management.service_requests.entity;

public enum ServiceRequestWorkOrderAction {
    FORWARDED_TO_MAINTENANCE_DEPARTMENT,
    SUBMITTED_TO_EXECUTIVE_COMMITTEE_FOR_APPROVAL,
    ASSIGNED_TO_COMPUTER_OPERATOR,
    FORWARDED_TO_ACCOUNTS_CLERK,
    SENT_FOR_INFORMATION_VERIFICATION,
    OTHER_ACTION
}
