package me.nimnakse.water_management.service_requests.entity;

public enum ServiceRequestCategory {
    WATER_SUPPLY_PRESSURE_ISSUES,
    WATER_QUALITY_SOURCE_ISSUES,
    WATER_BILLING_USAGE_METER_READING_ISSUES,
    CONNECTION_INSTALLATION_DISCONNECTION_RECONNECTION,
    OWNERSHIP_PREMISES_TARIFF_TRANSFERS,
    BULK_VALVE_BULK_METER_FAULTS_DAMAGES,
    SERVICE_PIPELINE_LEAKS_DAMAGES_BLOCKAGES,
    MAIN_PIPELINE_LEAKS_DAMAGES_BLOCKAGES,
    SERVICE_VALVE_SERVICE_METER_FAULTS_DAMAGES_BLOCKAGES,
    PIPE_BURSTS_WATER_LEAKAGES,
    TANK_AERATOR_FILTRATION_SYSTEM_ISSUES,
    WATER_PUMP_PUMP_HOUSE_FAULTS,
    ELECTRICAL_SYSTEM_GENERATOR_FAULTS,
    COMPUTER_INTERNET_CONNECTIVITY_FAULTS,
    ILLEGAL_WATER_SUPPLY_COMPLAINTS,
    STAFF_EMPLOYEE_CONDUCT_COMPLAINTS,
    DOCUMENT_REQUESTS_GENERAL_INQUIRIES,
    SUGGESTIONS_COMPLAINT_PROGRESS_INQUIRIES,
    BILLING_PAYMENT_CENTER_COMPLAINTS,
    OTHER
}
